# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ken.williams
email: kwillia@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
        postings of my various projects and code adventures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kenwilliams.info" # the base hostname & protocol for your site
twitter_username: kwilliams312
github_username:  kwilliams312

# Build settings
markdown: kramdown

# theme
theme: midnight
